---
- hosts: apache_servers
  become: yes
  tasks:
    - name: Copy Apache HTML page
      copy:
        src: ../html/apache.html
        dest: /var/www/html/index.html
        owner: ubuntu
        group: ubuntu
        mode: '0644'
