---
- name: Configure Nginx Server
  hosts: nginx_servers
  become: yes

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Copy Nginx HTML
      copy:
        src: "{{ playbook_dir }}/../html-content/files/nginx.html"
        dest: /var/www/html/index.html

    - name: Start Nginx
      service:
        name: nginx
        state: started
        enabled: yes
