---
- hosts: nginx_servers
  become: yes
  tasks:
    - name: Copy Nginx HTML page
      copy:
        src: ../html/nginx.html
        dest: /var/www/html/index.html
        owner: ubuntu
        group: ubuntu
        mode: '0644'
